version: '3'

services:
  api:
    # Build the api service using the Dockerfile
    #
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - minio
  minio:
    # Build the minio service 
    #
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: access-key
      MINIO_ROOT_PASSWORD: secret-key
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
      
volumes:
  minio_data:
